/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int OP_ADD = 5;
  /** RegularExpression Id. */
  int OP_SUB = 6;
  /** RegularExpression Id. */
  int OP_MUL = 7;
  /** RegularExpression Id. */
  int OP_DIV = 8;
  /** RegularExpression Id. */
  int L_BRACE = 9;
  /** RegularExpression Id. */
  int R_BRACE = 10;
  /** RegularExpression Id. */
  int EOL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
  };

}
